# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js TypeScript project to Azure Function App - PROD

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-deploy:
    # Only run this workflow if the release is created from the main branch
    if: |
      github.event_name == 'workflow_dispatch' || 
      (github.event_name == 'release' && github.event.release.target_commitish == 'main')
    uses: vestfoldfylke/shared/.github/workflows/deploy-az-app-service-node.yml@main
    with:
      azure_appname: 'samhandling-user-management'
      azure_functionapp_package_path: '.'
    secrets:
      azure_publishprofile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_PROD }}
