# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and test Node.js TypeScript project - TEST

on:
  push:
    branches-ignore:
      - 'release*'

env:
  NODE_VERSION: '22.x' # set this to the node version to use

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 'Resolve Project Dependencies Using Npm'
        shell: bash
        run: |
          pushd './.'
          npm install
          npm run build --if-present
          npm run test --if-present
          popd
